### ISSUE TITLE
Question about the competition

### ISSUE THREAD

**Issue by FrontierBreaker** [ldkong1205/RoboDepth#6]
1. Can we used pretrained weights for backbone? 
2. Can we use augmentations which are not the same as the corruption types to generate KITTI-C?

Thanks~

**Comment by FrontierBreaker** [comment]
3. Can model ensemble be used?

**Comment by ldkong1205** [comment]
Hi @FrontierBreaker, thanks for your interest in our competition!

Regarding your questions:
1. Using pretrained weights for the backbone is allowed. Actually, there are some recent studies that use pre-training to improve the model's robustness. We believe this is a promising way for improving generalizability.
2. Designing new data augmentation techniques to improve the robustness is interesting. We encourage participants to explore this direction. However, as mentioned in the terms & conditions of this competition, *"any use of the 18 corruption types designed in this benchmark is strictly prohibited, including any atomic operation that is comprising any one of the mentioned corruptions"*. Please pay extra attention to this to avoid a possible penalty. Also, some recent works unveil that, although using a specific corruption operation as the augmentation during training might improve the performance of this corruption type, it is likely that the final scores will become lower since it tends to hurt the model's generalizability on other corruptions.
3. Model ensemble is a common trick for most academic competitions and is also allowed in this competition.

**Comment by FrontierBreaker** [comment]
Thanks for your timely reply!

**Comment by ArgentumHook** [comment]
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/tmp/codalab/tmpwRT30w/run/program/evaluate.py", line 107, in 
    pred_disps = np.load(submit_path, fix_imports=True, encoding='latin1', allow_pickle=True)["data"]
  File "/opt/conda/lib/python3.9/site-packages/numpy/lib/npyio.py", line 243, in __getitem__
    return format.read_array(bytes,
  File "/opt/conda/lib/python3.9/site-packages/numpy/lib/format.py", line 747, in read_array
    array = pickle.load(fp, **pickle_kwargs)
ModuleNotFoundError: No module named 'torch'

Is there an abnormality in the backend runtime environment?

**Comment by ldkong1205** [comment]
Hi @ArgentumHook, could you check if you have installed PyTorch into your environment? You can check this via the following command:
```
conda env list
```

**Comment by ldkong1205** [comment]
Hi @ArgentumHook, if so then please ensure that your environment has been activated when running the code. Let me know if you have any problems.
