### ISSUE TITLE
Valid data augmentation

### ISSUE THREAD

**Issue by aaron-h-code** [ldkong1205/RoboDepth#7]
Hi @ldkong1205 , on the main page we found a description regarding data augmentation: 
```
"2. The theme of this competition is to probe the out-of-distribution robustness of depth estimation models. Theorefore, any use of the 18 corruption types designed in this benchmark is strictly prohibited, including any atomic operation that is comprising any one of the mentioned corruptions."
```

Does it mean that we are **not** allowed to use (any of) the 18 corruption provided in the "corruption/create.py" as data augmentation to train our model? Other type of data augmentation is allowed to use to train the model?

Thank you.

**Comment by ldkong1205** [comment]
Hi @aaron-h-code, thanks for asking this question!

Designing new data augmentation techniques to improve OoD robustness is an interesting topic. We encourage participants to explore this direction.

However, as mentioned in the terms & conditions of this competition, *"any use of the 18 corruption types designed in this benchmark is strictly prohibited, including any atomic operation that is comprising any one of the mentioned corruptions".* Please pay extra attention to this to avoid a possible penalty.

Therefore, as long as your data augmentation technique is not stemmed from the 18 corruption types, you are free to use it during model training.

Also, as has been replied in [this](https://github.com/ldkong1205/RoboDepth/issues/6) issue: some recent works unveil that, although using a specific corruption operation as the augmentation during training might improve the performance of certain corruption types, it is likely that the final scores will become lower since it tends to hurt the model's generalizability on other corruptions.

**Comment by ldkong1205** [comment]
Hi @aaron-h-code, I am closing this issue now. Feel free to open a new one if you have any questions. Thanks!
