### ISSUE TITLE
Must I use the backbones provided in the model zoo?

### ISSUE THREAD

**Issue by xuanlongORZ** [ldkong1205/RoboDepth#9]
Since more SOTA are updating performance on clean mono-depth datasets, I don't know if using the backbones provided in the model zoo is a must.

**Comment by ldkong1205** [comment]
Hi @xuanlongORZ, thanks for your question!

Using the backbone in the model zoo is not a must. I believe this should depend on your purpose. For example, if you are going to design a more robust depth estimation model, then you can just follow the best-performing ones in our model zoo and design new techniques upon them.

Since we are adding more and more depth estimation models into the benchmark, you can just copy the numbers from the benchmark when comparing your model. All models evaluated are from public resources or trained with official configurations so that they are directly comparable.

Hope the above answers your question. Let us know if you want to know more ~
